dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
dotenv: .env
networks:
  default: development
  rinkbey:
    eth_usd_price_feed: "0x..."
    verify: True
  development:
    verify: False
  ganache-local:
    verify: False
    kovan:
    mainnet:
wallets:
  from_key: ${PRIVATE_KEY}